comment "Remove existing items";
removeAllWeapons player;
removeAllItems player;
removeAllAssignedItems player;
removeUniform player;
removeVest player;
removeBackpack player;
removeHeadgear player;
removeGoggles player;
{player unassignItem _x;player removeItem _x} forEach assignedItems player;

comment "Add weapons";
player addWeapon "UK3CB_BAF_L85A3";
player addPrimaryWeaponItem "UK3CB_BAF_LLM_IR_Tan";
player addPrimaryWeaponItem "RKSL_optic_LDS";
player addPrimaryWeaponItem "UK3CB_BAF_556_30Rnd";
player addPrimaryWeaponItem "UK3CB_underbarrel_acc_grippod_t";
player addWeapon "UK3CB_BAF_L131A1";
player addHandgunItem "UK3CB_BAF_9_17Rnd";

comment "Add containers";
player forceAddUniform "16CSMR_UBACS_R";
player addVest "mpx_virtus_Medic_p";
player addBackpack "mpx_daysack7";

comment "Add items to containers";
for "_i" from 1 to 2 do {player addItemToUniform "ACE_EarPlugs";};
for "_i" from 1 to 4 do {player addItemToUniform "ACE_CableTie";};
player addItemToUniform "ACE_MapTools";
player addItemToUniform "BW_Facepaint";
player addItemToUniform "ACE_Flashlight_XL50";
player addItemToUniform "UK3CB_BAF_HMNVS";
player addItemToUniform "ACE_DAGR";
for "_i" from 1 to 10 do {player addItemToVest "ACE_epinephrine";};
for "_i" from 1 to 10 do {player addItemToVest "ACE_morphine";};
for "_i" from 1 to 10 do {player addItemToVest "ACE_adenosine";};
player addItemToVest "H2H_acc_bayo_L3A1";
for "_i" from 1 to 2 do {player addItemToVest "UK3CB_BAF_556_30Rnd";};
for "_i" from 1 to 2 do {player addItemToVest "SmokeShellPurple";};
for "_i" from 1 to 2 do {player addItemToVest "SmokeShell";};
for "_i" from 1 to 20 do {player addItemToBackpack "ACE_elasticBandage";};
for "_i" from 1 to 20 do {player addItemToBackpack "ACE_packingBandage";};
for "_i" from 1 to 20 do {player addItemToBackpack "ACE_quikclot";};
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_Canteen";};
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_MRE_MeatballsPasta";};
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_IR_Strobe_Item";};
for "_i" from 1 to 8 do {player addItemToBackpack "ACE_tourniquet";};
for "_i" from 1 to 20 do {player addItemToBackpack "kat_guedel";};
for "_i" from 1 to 5 do {player addItemToBackpack "kat_chestSeal";};
for "_i" from 1 to 5 do {player addItemToBackpack "kat_Pulseoximeter";};
player addItemToBackpack "ACE_personalAidKit";
player addItemToBackpack "ACE_surgicalKit";
player addItemToBackpack "ACE_EntrenchingTool";
for "_i" from 1 to 5 do {player addItemToBackpack "ACE_bodyBag";};
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_salineIV";};
for "_i" from 1 to 6 do {player addItemToBackpack "ACE_salineIV_500";};
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_salineIV_250";};
player addItemToBackpack "kat_accuvac";
for "_i" from 1 to 10 do {player addItemToBackpack "kat_larynx";};
player addItemToBackpack "UK3CB_BAF_H_Beret_RAMC";
player addHeadgear "mpx_cobra_scrim";

comment "Add items";
player linkItem "ItemMap";
player linkItem "ItemCompass";
player linkItem "ItemWatch";
