comment "Remove existing items";
removeAllWeapons player;
removeAllItems player;
removeAllAssignedItems player;
removeUniform player;
removeVest player;
removeBackpack player;
removeHeadgear player;
removeGoggles player;
{player unassignItem _x;player removeItem _x} forEach assignedItems player;

comment "Add weapons";
player addWeapon "UK3CB_BAF_L131A1";
player addHandgunItem "UK3CB_BAF_Flashlight_L131A1";
player addHandgunItem "UK3CB_BAF_9_17Rnd";

comment "Add containers";
player forceAddUniform "UK3CB_BAF_U_HeliPilotCoveralls_RAF";
player addVest "UK3CB_V_Pilot_Vest";
player addBackpack "rhsusf_eject_Parachute_backpack";

comment "Add items to containers";
for "_i" from 1 to 4 do {player addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 2 do {player addItemToUniform "ACE_tourniquet";};
player addItemToUniform "ACE_MapTools";
for "_i" from 1 to 2 do {player addItemToUniform "ACE_EarPlugs";};
player addItemToUniform "ACE_Chemlight_Shield";
for "_i" from 1 to 2 do {player addItemToUniform "ACE_packingBandage";};
player addItemToUniform "ACE_Flashlight_XL50";
player addItemToUniform "ACE_DAGR";
player addItemToUniform "BW_Facepaint";
player addItemToUniform "Chemlight_red";
player addItemToVest "ACRE_PRC343";
for "_i" from 1 to 2 do {player addItemToVest "ACRE_PRC152";};
for "_i" from 1 to 2 do {player addItemToVest "ACE_Canteen";};
player addItemToVest "ACE_MRE_MeatballsPasta";
player addItemToVest "ACE_MRE_BeefStew";
player addItemToVest "ACE_IR_Strobe_Item";
for "_i" from 1 to 2 do {player addItemToVest "UK3CB_BAF_9_17Rnd";};
player addItemToVest "SmokeShellPurple";
player addItemToVest "SmokeShellGreen";
player addItemToVest "SmokeShellBlue";
for "_i" from 1 to 2 do {player addItemToVest "SmokeShell";};
player addHeadgear "RHS_jetpilot_usaf";

comment "Add items";
player linkItem "ItemMap";
player linkItem "ItemCompass";
player linkItem "ACE_Altimeter";
player linkItem "ItemGPS";
