removeAllItems player;
removeAllWeapons player;
removeBackpack player;
clearBackpackCargo player;
clearAllItemsFromBackpack player;
removeUniform player;
removeVest player;
removeHeadgear player;
removeGoggles player;
{player unassignItem _x;player removeItem _x} forEach assignedItems player;

player forceAddUniform "mpx_mtp_marine_uniform_kr";
player addHeadgear "mpx_cobra_catseyes";
player addVest "mpx_virtus_medic_p";
player addBackpack "mpx_daysack7";
player addGoggles "G_Respirator_white_F";
for "_i" from 1 to 10 do {player addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 6 do {player addItemToUniform "ACE_elasticBandage";};
for "_i" from 1 to 6 do {player addItemToUniform "ACE_quikclot";};
player addItemToUniform "ACE_EarPlugs";
for "_i" from 1 to 6 do {player addItemToUniform "ACE_packingBandage";};
for "_i" from 1 to 2 do {player addItemToUniform "ACE_tourniquet";};
player addItemToUniform "US_Facepaint";
player addItemToVest "ItemcTabHCam";
for "_i" from 1 to 10 do {player addItemToVest "ACE_fieldDressing";};
for "_i" from 1 to 10 do {player addItemToVest "ACE_elasticBandage";};
for "_i" from 1 to 10 do {player addItemToVest "ACE_quikclot";};
for "_i" from 1 to 8 do {player addItemToVest "ACE_epinephrine";};
for "_i" from 1 to 12 do {player addItemToVest "ACE_morphine";};
for "_i" from 1 to 10 do {player addItemToVest "ACE_packingBandage";};
for "_i" from 1 to 8 do {player addItemToVest "ACE_adenosine";};
for "_i" from 1 to 8 do {player addItemToVest "ACE_atropine";};
player addItemToVest "ACRE_PRC343";
player addItemToVest "ACRE_PRC152";
for "_i" from 1 to 3 do {player addItemToVest "UK3CB_BAF_9_17Rnd";};
for "_i" from 1 to 2 do {player addItemToBackpack "SmokeShell";};
for "_i" from 1 to 2 do {player addItemToBackpack "SmokeShellPurple";};
for "_i" from 1 to 2 do {player addItemToBackpack "SmokeShellBlue";};
for "_i" from 1 to 2 do {player addItemToBackpack "SmokeShellGreen";};
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_Chemlight_HiBlue";};
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_Chemlight_HiGreen";};
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_Chemlight_HiWhite";};
player addItemToBackpack "KAT_CrossPanel";
player addItemToBackpack "ACE_MapTools";
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_CableTie";};
player addItemToBackpack "UK3CB_BAF_HMNVS";
player addItemToBackpack "UK3CB_BAF_G_Tactical_Clear";
player addItemToBackpack "ACE_EntrenchingTool";
player addItemToBackpack "G_CBRN_M50";
player addItemToBackpack "UK3CB_BAF_H_Beret_RLC_Commando_PRR";
player addItemToBackpack "ACE_Flashlight_MX991";
player addItemToBackpack "ACE_MRE_CreamChickenSoup";
player addItemToBackpack "ACE_Canteen";
player addItemToBackpack "ACE_personalAidKit";
player addItemToBackpack "ACE_surgicalKit";
for "_i" from 1 to 20 do {player addItemToBackpack "ACE_packingBandage";};
for "_i" from 1 to 5 do {player addItemToBackpack "ACE_tourniquet";};
for "_i" from 1 to 6 do {player addItemToBackpack "ACE_salineIV_500";};
for "_i" from 1 to 12 do {player addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 10 do {player addItemToBackpack "KAT_larynx";};
for "_i" from 1 to 8 do {player addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 20 do {player addItemToBackpack "ACE_quikclot";};
for "_i" from 1 to 20 do {player addItemToBackpack "ACE_elasticBandage";};
for "_i" from 1 to 20 do {player addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 6 do {player addItemToBackpack "ACE_adenosine";};
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_atropine";};
player addItemToBackpack "KAT_X_AED";
player addItemToBackpack "KAT_accuvac";
for "_i" from 1 to 5 do {player addItemToBackpack "KAT_ChestSeal";};
for "_i" from 1 to 2 do {player addItemToBackpack "KAT_Pulseoximeter";};
for "_i" from 1 to 6 do {player addItemToBackpack "adv_aceSplint_splint";};
for "_i" from 1 to 6 do {player addItemToBackpack "ACE_salineIV_250";};
player addWeapon "ACE_Vector";
player addWeapon "UK3CB_BAF_L131A1";
player addHandgunItem "UK3CB_BAF_Flashlight_L131A1";
player linkItem "ItemMap";
player linkItem "ItemCompass";
player linkItem "ItemWatch";
player linkItem "ItemcTab";
[player,"UK3CB_BAF_Insignia_RedCross"] call bis_fnc_setUnitInsignia;