removeAllWeapons player;
removeAllItems player;
removeAllAssignedItems player;
removeUniform player;
removeVest player;
removeBackpack player;
removeHeadgear player;
removeGoggles player;
{player unassignItem _x;player removeItem _x} forEach assignedItems player;

player forceAddUniform "UK3CB_BAF_U_CombatUniform_MTP_RM";
player addItemToUniform "ACE_EarPlugs";
for "_i" from 1 to 6 do {player addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 6 do {player addItemToUniform "ACE_elasticBandage";};
for "_i" from 1 to 6 do {player addItemToUniform "ACE_quikclot";};
player addItemToUniform "ACE_MapTools";
for "_i" from 1 to 6 do {player addItemToUniform "ACE_packingBandage";};
for "_i" from 1 to 2 do {player addItemToUniform "ACE_tourniquet";};
player addItemToUniform "ACE_Flashlight_MX991";
player addItemToUniform "US_Facepaint";
player addItemToUniform "ACE_RangeCard";
player addItemToUniform "ItemcTabHCam";
player addVest "UK3CB_BAF_V_Osprey_Marksman_A";
for "_i" from 1 to 2 do {player addItemToVest "SmokeShell";};
for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
player addItemToVest "Chemlight_blue";
for "_i" from 1 to 8 do {player addItemToVest "UK3CB_BAF_338_5Rnd";};
player addItemToVest "ACRE_PRC343";
player addBackpack "UK3CB_BAF_B_Bergen_MTP_Rifleman_L_C";
player addItemToBackpack "UK3CB_BAF_H_Beret_RM_Bootneck_PRR";
player addItemToBackpack "UK3CB_BAF_HMNVS";
player addItemToBackpack "UK3CB_BAF_G_Tactical_Clear";
player addItemToBackpack "UK3CB_BAF_H_Boonie_MTP_PRR";
player addItemToBackpack "ACE_EntrenchingTool";
player addItemToBackpack "ACE_DAGR";
player addItemToBackpack "ACE_Kestrel4500";
player addItemToBackpack "G_CBRN_M50";
for "_i" from 1 to 4 do {player addItemToBackpack "UK3CB_BAF_338_5Rnd";};
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_CableTie";};
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_Canteen";};
player addHeadgear "UK3CB_BAF_H_Mk7_Scrim_A";
player addGoggles "G_Bandanna_khk";

player addWeapon "UK3CB_BAF_L115A3";
player addPrimaryWeaponItem "RKSL_optic_PMII_525";
player addWeapon "ACE_Vector";

player linkItem "ItemMap";
player linkItem "ItemCompass";
player linkItem "ItemWatch";
player linkItem "ItemGPS";

[player,"UK3CB_BAF_Insignia_RMDagger_1"] call bis_fnc_setUnitInsignia;