removeAllItems player;
removeAllWeapons player;
removeBackpack player;
clearBackpackCargo player;
clearAllItemsFromBackpack player;
removeUniform player;
removeVest player;
removeHeadgear player;
removeGoggles player;
{player unassignItem _x;player removeItem _x} forEach assignedItems player;

player forceAddUniform "UK3CB_BAF_U_CombatUniform_MTP_RM";
player addHeadgear "UK3CB_BAF_H_Mk7_Scrim_A";
player addVest "UK3CB_BAF_V_Osprey_Rifleman_B";
player addBackpack "UK3CB_BAF_B_Kitbag_MTP";
for "_i" from 1 to 10 do {player addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 6 do {player addItemToUniform "ACE_elasticBandage";};
for "_i" from 1 to 6 do {player addItemToUniform "ACE_quikclot";};
player addItemToUniform "ACE_EarPlugs";
for "_i" from 1 to 6 do {player addItemToUniform "ACE_packingBandage";};
for "_i" from 1 to 2 do {player addItemToUniform "ACE_tourniquet";};
player addItemToUniform "US_Facepaint";
player addItemToVest "ItemcTabHCam";
player addItemToVest "ACRE_PRC343";
for "_i" from 1 to 6 do {player addItemToVest "RHS_MAG_30Rnd_556x45_Mk318_Stanag";};
for "_i" from 1 to 2 do {player addItemToVest "UK3CB_BAF_9_17Rnd";};
for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
for "_i" from 1 to 2 do {player addItemToVest "SmokeShell";};
player addItemToBackpack "ACE_MapTools";
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_CableTie";};
player addItemToBackpack "UK3CB_BAF_HMNVS";
player addItemToBackpack "milgp_f_face_shield_shemagh_khk";
player addItemToBackpack "ACE_EntrenchingTool";
player addItemToBackpack "G_CBRN_M50";
player addItemToBackpack "UK3CB_BAF_H_Beret_RM_Bootneck_PRR";
player addItemToBackpack "UK3CB_BAF_H_Boonie_MTP_PRR";
player addItemToBackpack "ACE_Flashlight_MX991";
player addItemToBackpack "ACE_MRE_ChickenTikkaMasala";
player addItemToBackpack "ACE_Canteen";
player addItemToBackpack "KNB_Notebook";
player addItemToBackpack "UK3CB_BAF_9_17Rnd";
for "_i" from 1 to 4 do {player addItemToBackpack "RHS_MAG_30Rnd_556x45_Mk318_Stanag";};
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_Chemlight_HiBlue";};
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_Chemlight_HiGreen";};
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_Chemlight_HiRed";};
for "_i" from 1 to 2 do {player addItemToBackpack "B_IR_Grenade";};
for "_i" from 1 to 15 do {player addItemToBackpack "ACE_quikclot";};
for "_i" from 1 to 15 do {player addItemToBackpack "ACE_elasticBandage";};
for "_i" from 1 to 15 do {player addItemToBackpack "ACE_packingBandage";};
for "_i" from 1 to 25 do {player addItemToBackpack "ACE_fieldDressing";};
for "_i" from 1 to 6 do {player addItemToBackpack "ACE_morphine";};
for "_i" from 1 to 4 do {player addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 2 do {player addItemToBackpack "KAT_larynx";};
for "_i" from 1 to 2 do {player addItemToBackpack "adv_ACESplint_Splint";};
player addWeapon "SBS_L119A1_BLK";
player addPrimaryWeaponItem "RHSUSF_ACC_ANPEQ15_BK";
player addPrimaryWeaponItem "RKSL_optic_LDS";
player addPrimaryWeaponItem "SBS_SF_SILENCER";
player addWeapon "UK3CB_BAF_L131A1";
player addHandgunItem "UK3CB_BAF_Flashlight_L131A1";
player addHandgunItem "Muzzle_SNDS_L";
player addWeapon "ACE_VectorDay";
player linkItem "ItemMap";
player linkItem "ItemCompass";
player linkItem "ItemWatch";
[player,"UK3CB_BAF_Insignia_RMDagger_1"] call bis_fnc_setUnitInsignia;

