removeAllItems player;
removeAllWeapons player;
removeBackpack player;
clearBackpackCargo player;
clearAllItemsFromBackpack player;
removeUniform player;
removeVest player;
removeHeadgear player;
removeGoggles player;
{player unassignItem _x;player removeItem _x} forEach assignedItems player;

player forceAddUniform "mpx_mtp_marine_uniform_k";
player addHeadgear "mpx_cobra_catseyes";
player addVest "mpx_virtus_admin_p";
player addBackpack "mpx_daysack9";
for "_i" from 1 to 10 do {player addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 6 do {player addItemToUniform "ACE_elasticBandage";};
for "_i" from 1 to 6 do {player addItemToUniform "ACE_quikclot";};
player addItemToUniform "ACE_EarPlugs";
for "_i" from 1 to 6 do {player addItemToUniform "ACE_packingBandage";};
for "_i" from 1 to 2 do {player addItemToUniform "ACE_tourniquet";};
player addItemToUniform "US_Facepaint";
player addItemToVest "ItemcTabHCam";
for "_i" from 1 to 2 do {player addItemToVest "ACE_morphine";};
player addItemToVest "ACE_epinephrine";
player addItemToVest "ACRE_PRC343";
for "_i" from 1 to 2 do {player addItemToVest "UK3CB_BAF_9_17Rnd";};
for "_i" from 1 to 2 do {player addItemToVest "UK3CB_BAF_556_30Rnd_T";};
for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
for "_i" from 1 to 2 do {player addItemToVest "SmokeShell";};
for "_i" from 1 to 4 do {player addItemToVest "UK3CB_BAF_556_30Rnd";};
for "_i" from 1 to 3 do {player addItemToBackpack "UK3CB_BAF_1Rnd_HE_Grenade_Shell";};
for "_i" from 1 to 2 do {player addItemToBackpack "1Rnd_SmokeRed_Grenade_shell";};
player addItemToBackpack "1Rnd_SmokePurple_Grenade_shell";
player addItemToBackpack "1Rnd_SmokeBlue_Grenade_shell";
player addItemToBackpack "1Rnd_SmokeGreen_Grenade_shell";
for "_i" from 1 to 2 do {player addItemToBackpack "1Rnd_Smoke_Grenade_shell";};
player addItemToBackpack "ACE_MapTools";
player addItemToBackpack "ACRE_PRC152";
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_CableTie";};
player addItemToBackpack "UK3CB_BAF_HMNVS";
player addItemToBackpack "UK3CB_BAF_G_Tactical_Clear";
player addItemToBackpack "ACE_EntrenchingTool";
player addItemToBackpack "G_CBRN_M50";
player addItemToBackpack "UK3CB_BAF_H_Beret_RM_Officer_PRR";
player addItemToBackpack "ACE_Flashlight_MX991";
player addItemToBackpack "ACE_MRE_CreamChickenSoup";
player addItemToBackpack "BatlskinCobraVisor";
player addItemToBackpack "ACE_Canteen";
player addItemToBackpack "KNB_Notebook";
player addItemToBackpack "UK3CB_BAF_9_17Rnd";
for "_i" from 1 to 2 do {player addItemToBackpack "UK3CB_BAF_556_30Rnd_T";};
for "_i" from 1 to 4 do {player addItemToBackpack "UK3CB_BAF_556_30Rnd";};
for "_i" from 1 to 2 do {player addItemToBackpack "SmokeShellBlue";};
for "_i" from 1 to 2 do {player addItemToBackpack "SmokeShellGreen";};
for "_i" from 1 to 2 do {player addItemToBackpack "SmokeShellPurple";};
for "_i" from 1 to 2 do {player addItemToBackpack "SmokeShellRed";};
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_Chemlight_HiBlue";};
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_Chemlight_HiGreen";};
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_Chemlight_HiRed";};
player addWeapon "UK3CB_BAF_L85A2_UGL_HWS";
player addPrimaryWeaponItem "UK3CB_BAF_LLM_Flashlight_Black";
player addPrimaryWeaponItem "RKSL_optic_LDS";
player addWeapon "UK3CB_BAF_L131A1";
player addHandgunItem "UK3CB_BAF_Flashlight_L131A1";
player addWeapon "ACE_Vector";
player linkItem "ItemMap";
player linkItem "ItemCompass";
player linkItem "ItemWatch";
player linkItem "ItemcTab";
[player,"UK3CB_BAF_Insignia_RMDagger_1"] call bis_fnc_setUnitInsignia;
