removeAllItems player;
removeAllWeapons player;
removeBackpack player;
clearBackpackCargo player;
clearAllItemsFromBackpack player;
removeUniform player;
removeVest player;
removeHeadgear player;
removeGoggles player;
{player unassignItem _x;player removeItem _x} forEach assignedItems player;

player forceAddUniform "mpx_mtp_marine_uniform_k";
player addHeadgear "mpx_cobra_catseyes";
player addVest "mpx_virtus_taco_p";
player addBackpack "mpx_daysack8";
for "_i" from 1 to 10 do {player addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 6 do {player addItemToUniform "ACE_elasticBandage";};
for "_i" from 1 to 6 do {player addItemToUniform "ACE_quikclot";};
player addItemToUniform "ACE_EarPlugs";
for "_i" from 1 to 6 do {player addItemToUniform "ACE_packingBandage";};
for "_i" from 1 to 2 do {player addItemToUniform "ACE_tourniquet";};
player addItemToUniform "US_Facepaint";
player addItemToVest "para_acc_L3A1_bayo";
player addItemToVest "ItemcTabHCam";
player addItemToVest "ACRE_PRC343";
for "_i" from 1 to 4 do {player addItemToVest "UK3CB_BAF_556_30Rnd";};
for "_i" from 1 to 2 do {player addItemToVest "UK3CB_BAF_9_17Rnd";};
for "_i" from 1 to 2 do {player addItemToVest "UK3CB_BAF_556_30Rnd_T";};
for "_i" from 1 to 2 do {player addItemToVest "HandGrenade";};
for "_i" from 1 to 2 do {player addItemToVest "SmokeShell";};
player addItemToBackpack "ACE_MapTools";
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_CableTie";};
player addItemToBackpack "UK3CB_BAF_HMNVS";
player addItemToBackpack "UK3CB_BAF_G_Tactical_Clear";
player addItemToBackpack "ACE_EntrenchingTool";
player addItemToBackpack "G_CBRN_M50";
player addItemToBackpack "UK3CB_BAF_H_Beret_RM_Bootneck_PRR";
player addItemToBackpack "ACE_Flashlight_MX991";
player addItemToBackpack "ACE_MRE_CreamChickenSoup";
player addItemToBackpack "ACE_Canteen";
player addItemToBackpack "UK3CB_BAF_9_17Rnd";
player addItemToBackpack "ACE_RangeTable_82mm";
player addItemToBackpack "ACE_Kestrel4500";
for "_i" from 1 to 4 do {player addItemToBackpack "UK3CB_BAF_556_30Rnd";};
for "_i" from 1 to 2 do {player addItemToBackpack "UK3CB_BAF_556_30Rnd_T";};
for "_i" from 1 to 3 do {player addItemToBackpack "UK3CB_BAF_1Rnd_60mm_Mo_Shells";};
for "_i" from 1 to 2 do {player addItemToBackpack "UK3CB_BAF_1Rnd_60mm_Mo_Smoke_White";};
player addWeapon "UK3CB_BAF_L85A2_RIS";
player addPrimaryWeaponItem "UK3CB_BAF_LLM_Flashlight_Black";
player addPrimaryWeaponItem "UK3CB_UNDERBARREL_ACC_GRIPPOD";
player addPrimaryWeaponItem "RKSL_optic_LDS";
player addWeapon "UK3CB_BAF_L131A1";
player addHandgunItem "UK3CB_BAF_Flashlight_L131A1";
player addWeapon "UK3CB_BAF_M6";
player linkItem "ItemMap";
player linkItem "ItemCompass";
player linkItem "ItemWatch";
[player,"UK3CB_BAF_Insignia_RMDagger_1"] call bis_fnc_setUnitInsignia;