comment "Remove existing items";
removeAllWeapons player;
removeAllItems player;
removeAllAssignedItems player;
removeUniform player;
removeVest player;
removeBackpack player;
removeHeadgear player;
removeGoggles player;
{player unassignItem _x;player removeItem _x} forEach assignedItems player;

comment "Add weapons";
player addWeapon "UK3CB_BAF_L85A3";
player addPrimaryWeaponItem "UK3CB_BAF_LLM_IR_Tan";
player addPrimaryWeaponItem "RKSL_optic_LDS";
player addPrimaryWeaponItem "UK3CB_BAF_556_30Rnd";
player addPrimaryWeaponItem "UK3CB_underbarrel_acc_grippod_t";
player addWeapon "UK3CB_BAF_L131A1";
player addHandgunItem "UK3CB_BAF_9_17Rnd";

comment "Add containers";
player forceAddUniform "2PARA_UBACS_R";
player addVest "mpx_virtus_Medic_p";
player addBackpack "UK3CB_BAF_B_Bergen_MTP_Medic_L_B";

comment "Add items to containers";
for "_i" from 1 to 4 do {player addItemToUniform "ACE_fieldDressing";};
for "_i" from 1 to 2 do {player addItemToUniform "ACE_tourniquet";};
player addItemToUniform "ACE_MapTools";
for "_i" from 1 to 2 do {player addItemToUniform "ACE_EarPlugs";};
player addItemToUniform "ACE_Chemlight_Shield";
for "_i" from 1 to 2 do {player addItemToUniform "ACE_packingBandage";};
player addItemToUniform "ACE_Flashlight_XL50";
player addItemToUniform "ACE_DAGR";
player addItemToUniform "BW_Facepaint";
for "_i" from 1 to 2 do {player addItemToUniform "ACE_CableTie";};
player addItemToUniform "Chemlight_red";
player addItemToVest "ACRE_PRC343";
for "_i" from 1 to 4 do {player addItemToVest "ACE_morphine";};
for "_i" from 1 to 5 do {player addItemToVest "UK3CB_BAF_556_30Rnd";};
player addItemToVest "UK3CB_BAF_556_30Rnd_T";
player addItemToVest "SmokeShell";
player addItemToVest "rhs_mag_m67";
player addItemToVest "UK3CB_BAF_9_17Rnd";
for "_i" from 1 to 2 do {player addItemToVest "kat_Painkiller";};
player addItemToVest "SmokeShellPurple";
player addItemToBackpack "ACE_MRE_BeefStew";
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_Canteen";};
player addItemToBackpack "UK3CB_BAF_H_Beret_PR";
player addItemToBackpack "ACE_MRE_ChickenTikkaMasala";
for "_i" from 1 to 30 do {player addItemToBackpack "ACE_packingBandage";};
for "_i" from 1 to 30 do {player addItemToBackpack "ACE_elasticBandage";};
for "_i" from 1 to 8 do {player addItemToBackpack "ACE_tourniquet";};
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_salineIV_500";};
for "_i" from 1 to 4 do {player addItemToBackpack "kat_chestSeal";};
for "_i" from 1 to 4 do {player addItemToBackpack "ACE_splint";};
for "_i" from 1 to 10 do {player addItemToBackpack "kat_guedel";};
for "_i" from 1 to 2 do {player addItemToBackpack "ACE_WaterBottle";};
player addHeadgear "mpx_cobra_scrim";

comment "Add items";
player linkItem "ItemMap";
player linkItem "ItemCompass";
player linkItem "ItemWatch";
